package compiler

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"strconv"
	"strings"
	"unicode"
)

// Compile converts one Northframe component into a native Go SSR renderer.
func Compile(packageName, componentName string, source []byte) ([]byte, error) {
	if !identifier.MatchString(packageName) {
		return nil, fmt.Errorf("invalid package name %q", packageName)
	}
	name := exportedName(componentName)
	parsed, err := parseComponent(name, string(source))
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer
	output.WriteString("// Code generated by Northframe. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	output.WriteString("import (\n\t\"io\"\n")
	if nodesUseRuntime(parsed.Children) {
		output.WriteString("\n\t\"northframe.dev/northframe/pkg/web\"\n")
	}
	for _, componentImport := range parsed.Imports {
		fmt.Fprintf(&output, "\t%s %s\n", componentImport.Alias, strconv.Quote(componentImport.Path))
	}
	output.WriteString(")\n\n")
	fmt.Fprintf(&output, "type %sProps struct {\n", parsed.Name)
	for _, field := range parsed.Props {
		fmt.Fprintf(&output, "\t%s %s\n", field.Name, field.Type)
	}
	if nodesHaveSlot(parsed.Children) {
		output.WriteString("\tContent web.Fragment `json:\"-\"`\n")
	}
	output.WriteString("}\n\n")
	fmt.Fprintf(&output, "func Render%s(w io.Writer, props %sProps) error {\n", parsed.Name, parsed.Name)
	writeNodes(&output, parsed.Children, map[string]bool{}, "props.Content", clientPrefix(parsed.Name))
	output.WriteString("\treturn nil\n}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated renderer: %w\n%s", err, output.String())
	}
	return formatted, nil
}

// CompileRoute generates a renderer whose props are owned by the colocated
// page.north.go or layout.north.go package.
func CompileRoute(packageName, componentName string, source []byte, routeAlias, routeImport, kind string) ([]byte, error) {
	if !identifier.MatchString(packageName) || !identifier.MatchString(routeAlias) {
		return nil, fmt.Errorf("invalid generated package or route alias")
	}
	if kind != "page" && kind != "layout" {
		return nil, fmt.Errorf("invalid route component kind %q", kind)
	}
	name := exportedName(componentName)
	parsed, err := parseComponent(name, string(source))
	if err != nil {
		return nil, err
	}

	propsType := "PageProps"
	if kind == "layout" {
		propsType = "LayoutProps"
	}
	var output bytes.Buffer
	output.WriteString("// Code generated by Northframe. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	output.WriteString("import (\n\t\"io\"\n")
	if kind == "layout" || nodesUseRuntime(parsed.Children) {
		output.WriteString("\n\t\"northframe.dev/northframe/pkg/web\"\n")
	}
	fmt.Fprintf(&output, "\t%s %s\n", routeAlias, strconv.Quote(routeImport))
	output.WriteString(")\n\n")
	fmt.Fprintf(&output, "func Render%s(w io.Writer, props %s.%s", parsed.Name, routeAlias, propsType)
	slotExpression := ""
	if kind == "layout" {
		output.WriteString(", content web.Fragment")
		slotExpression = "content"
	}
	output.WriteString(") error {\n")
	writeNodes(&output, parsed.Children, map[string]bool{}, slotExpression, clientPrefix(parsed.Name))
	output.WriteString("\treturn nil\n}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated route renderer: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func nodesUseRuntime(nodes []node) bool {
	for _, raw := range nodes {
		switch current := raw.(type) {
		case exprNode, ifNode, slotNode, propsNode:
			return true
		case eachNode:
			if nodesUseRuntime(current.Children) {
				return true
			}
		case componentNode:
			if nodesUseRuntime(current.Children) {
				return true
			}
		}
	}
	return false
}

func writeNodes(output *bytes.Buffer, nodes []node, locals map[string]bool, slotExpression, propsMarker string) {
	for _, raw := range nodes {
		switch current := raw.(type) {
		case textNode:
			writeLiteral(output, current.Value)
		case exprNode:
			fmt.Fprintf(output, "\tif err := web.WriteEscaped(w, %s); err != nil { return err }\n", goExpression(current.Expression, locals))
		case styleNode:
			writeLiteral(output, "<style>"+current.Value+"</style>")
		case slotNode:
			if slotExpression != "" {
				fmt.Fprintf(output, "\tif %s != nil { if err := %s(w); err != nil { return err } }\n", slotExpression, slotExpression)
			}
		case propsNode:
			fmt.Fprintf(output, "\tif err := web.WriteClientProps(w, %s, props); err != nil { return err }\n", strconv.Quote(propsMarker))
		case ifNode:
			fmt.Fprintf(output, "\tif %s {\n", goCondition(current.Condition, locals))
			writeNodes(output, current.Children, locals, slotExpression, propsMarker)
			output.WriteString("\t}\n")
		case eachNode:
			fmt.Fprintf(output, "\tfor _, %s := range %s {\n", current.Item, goExpression(current.Collection, locals))
			nested := cloneLocals(locals)
			nested[current.Item] = true
			writeNodes(output, current.Children, nested, slotExpression, propsMarker)
			output.WriteString("\t}\n")
		case componentNode:
			writeComponentNode(output, current, locals, propsMarker)
		}
	}
}

func writeComponentNode(output *bytes.Buffer, current componentNode, locals map[string]bool, propsMarker string) {
	fmt.Fprintf(output, "\tif err := Render%s(w, %sProps{\n", current.Name, current.Name)
	for _, attribute := range current.Attributes {
		fmt.Fprintf(output, "\t\t%s: %s,\n", attribute.Name, componentAttributeExpression(attribute, locals))
	}
	if len(current.Children) > 0 {
		output.WriteString("\t\tContent: func(w io.Writer) error {\n")
		writeNodes(output, current.Children, locals, "", propsMarker)
		output.WriteString("\t\t\treturn nil\n\t\t},\n")
	}
	output.WriteString("\t}); err != nil { return err }\n")
}

func componentAttributeExpression(attribute componentAttribute, locals map[string]bool) string {
	if !attribute.Literal {
		return goExpression(attribute.Value, locals)
	}
	if attribute.Quoted {
		return strconv.Quote(attribute.Value)
	}
	return attribute.Value
}

func nodesHaveSlot(nodes []node) bool {
	for _, raw := range nodes {
		switch current := raw.(type) {
		case slotNode:
			return true
		case ifNode:
			if nodesHaveSlot(current.Children) {
				return true
			}
		case eachNode:
			if nodesHaveSlot(current.Children) {
				return true
			}
		case componentNode:
			if nodesHaveSlot(current.Children) {
				return true
			}
		}
	}
	return false
}

func writeLiteral(output *bytes.Buffer, value string) {
	if value == "" {
		return
	}
	fmt.Fprintf(output, "\tif _, err := io.WriteString(w, %s); err != nil { return err }\n", strconv.Quote(value))
}

func goExpression(expression string, locals map[string]bool) string {
	parsed, err := parser.ParseExpr(strings.TrimSpace(expression))
	if err != nil {
		return expression
	}
	ast.Inspect(parsed, func(node ast.Node) bool {
		identifier, ok := node.(*ast.Ident)
		if ok && identifier.Name == "Props" {
			identifier.Name = "props"
		}
		return true
	})
	var output bytes.Buffer
	if err := format.Node(&output, token.NewFileSet(), parsed); err != nil {
		return expression
	}
	return output.String()
}

func goCondition(condition string, locals map[string]bool) string {
	parsed, err := parser.ParseExpr(strings.TrimSpace(condition))
	if err != nil {
		return condition
	}
	negated := false
	if unary, ok := parsed.(*ast.UnaryExpr); ok && unary.Op == token.NOT {
		parsed = unary.X
		negated = true
	}
	if _, ok := parsed.(*ast.Ident); ok {
		truthy := "web.Truthy(" + goExpressionNode(parsed) + ")"
		if negated {
			return "!" + truthy
		}
		return truthy
	}
	if _, ok := parsed.(*ast.SelectorExpr); ok {
		truthy := "web.Truthy(" + goExpressionNode(parsed) + ")"
		if negated {
			return "!" + truthy
		}
		return truthy
	}
	return goExpression(condition, locals)
}

func goExpressionNode(expression ast.Expr) string {
	ast.Inspect(expression, func(node ast.Node) bool {
		identifier, ok := node.(*ast.Ident)
		if ok && identifier.Name == "Props" {
			identifier.Name = "props"
		}
		return true
	})
	var output bytes.Buffer
	_ = format.Node(&output, token.NewFileSet(), expression)
	return output.String()
}

func cloneLocals(input map[string]bool) map[string]bool {
	result := make(map[string]bool, len(input))
	for key, value := range input {
		result[key] = value
	}
	return result
}

func exportedName(value string) string {
	parts := strings.FieldsFunc(value, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		result.WriteRune(unicode.ToUpper(runes[0]))
		result.WriteString(string(runes[1:]))
	}
	if result.Len() == 0 {
		return "Component"
	}
	return result.String()
}
