package compiler

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

func generateRouter(packageName string, pages []routeView, layouts map[string]routeView, apiRoutes []apiRoute, errorPage *componentView, styles []byte, assets, clientAssets []publicAsset) ([]byte, error) {
	sort.Slice(pages, func(i, j int) bool { return pages[i].Path < pages[j].Path })
	aliases, imports := routeImports(pages, layouts, apiRoutes)

	var output bytes.Buffer
	output.WriteString("// Code generated by Northframe. DO NOT EDIT.\n\n")
	fmt.Fprintf(&output, "package %s\n\n", packageName)
	output.WriteString("import (\n\t\"bytes\"\n\t\"io\"\n\t\"net/http\"\n\n")
	for _, alias := range aliases {
		fmt.Fprintf(&output, "\t%s %s\n", alias, strconv.Quote(imports[alias]))
	}
	output.WriteString("\t\"github.com/JohnKinyanjui/northframe/pkg/web\"\n)\n\n")
	fmt.Fprintf(&output, "const appCSS = %s\n\n", strconv.Quote(string(styles)))
	writeAssetMap(&output, "publicAssets", assets)
	writeAssetMap(&output, "clientAssets", clientAssets)
	writeRouteRegistration(&output, pages, apiRoutes, errorPage, assets, clientAssets)
	for _, page := range pages {
		writePageMiddleware(&output, page, layouts)
		writePageRenderer(&output, page, layouts)
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated router: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func routeImports(pages []routeView, layouts map[string]routeView, apiRoutes []apiRoute) ([]string, map[string]string) {
	imports := map[string]string{}
	for _, page := range pages {
		imports[page.ImportAlias] = page.ImportPath
	}
	for _, layout := range layouts {
		imports[layout.ImportAlias] = layout.ImportPath
	}
	for _, route := range apiRoutes {
		imports[route.ImportAlias] = route.ImportPath
	}
	aliases := make([]string, 0, len(imports))
	for alias := range imports {
		aliases = append(aliases, alias)
	}
	sort.Strings(aliases)
	return aliases, imports
}

func writeAssetMap(output *bytes.Buffer, name string, assets []publicAsset) {
	if len(assets) == 0 {
		return
	}
	fmt.Fprintf(output, "var %s = map[string]web.Asset{\n", name)
	for _, asset := range assets {
		fmt.Fprintf(output, "\t%s: web.NewAsset([]byte(%s), %s),\n", strconv.Quote(asset.Path), strconv.Quote(string(asset.Content)), strconv.Quote(asset.ContentType))
	}
	output.WriteString("}\n\n")
}

func writeRouteRegistration(output *bytes.Buffer, pages []routeView, apiRoutes []apiRoute, errorPage *componentView, assets, clientAssets []publicAsset) {
	output.WriteString("func Register(app *web.App) {\n")
	if errorPage != nil {
		output.WriteString("\tapp.SetErrorRenderer(func(w io.Writer, page web.ErrorPage) error {\n")
		output.WriteString("\t\treturn RenderApplicationError(w, ApplicationErrorProps{Status: page.Status, Message: page.Message, Path: page.Path, RequestID: page.RequestID})\n")
		output.WriteString("\t})\n")
	}
	output.WriteString("\tapp.HandleFunc(\"GET /_northframe/app.css\", func(w http.ResponseWriter, _ *http.Request) { w.Header().Set(\"Content-Type\", \"text/css; charset=utf-8\"); _, _ = io.WriteString(w, appCSS) })\n")
	output.WriteString("\tapp.Handle(\"GET /_northframe/\", http.StripPrefix(\"/_northframe/\", web.BrowserHandler()))\n")
	if len(assets) > 0 {
		output.WriteString("\tapp.Handle(\"GET /public/\", http.StripPrefix(\"/public/\", web.PublicHandler(publicAssets)))\n")
		for _, asset := range assets {
			fmt.Fprintf(output, "\tapp.Handle(%q, web.PublicHandler(publicAssets))\n", "GET /"+asset.Path)
		}
	}
	if len(clientAssets) > 0 {
		output.WriteString("\tapp.Handle(\"GET /_northframe/components/\", http.StripPrefix(\"/_northframe/components/\", web.PublicHandler(clientAssets)))\n")
	}
	for _, page := range pages {
		variable := lowerFirst(page.Name) + "Middleware"
		fmt.Fprintf(output, "\t%s := %sMiddleware()\n", variable, page.Name)
		pattern := page.Path
		if pattern == "/" {
			pattern = "/{$}"
		}
		fmt.Fprintf(output, "\tapp.HandleFunc(%q, func(w http.ResponseWriter, r *http.Request) {\n", "GET "+pattern)
		output.WriteString("\t\tvar body bytes.Buffer\n")
		fmt.Fprintf(output, "\t\tif err := render%sRoute(&body, r); err != nil { app.HandleError(w, r, err); return }\n", page.Name)
		output.WriteString("\t\tw.Header().Set(\"Content-Type\", \"text/html; charset=utf-8\")\n\t\t_, _ = body.WriteTo(w)\n")
		fmt.Fprintf(output, "\t}, %s...)\n", variable)
		if page.HasActions {
			fmt.Fprintf(output, "\tfor _, action := range %s.PageActions() { app.HandleAction(%q, action, %s...) }\n", page.ImportAlias, page.Path, variable)
		}
	}
	for _, route := range apiRoutes {
		middleware := "nil"
		if route.HasMiddleware {
			variable := lowerFirst(exportedName(route.ImportAlias)) + "Middleware"
			fmt.Fprintf(output, "\t%s := %s.Middleware()\n", variable, route.ImportAlias)
			middleware = variable
		}
		for _, method := range route.Methods {
			if middleware == "nil" {
				fmt.Fprintf(output, "\tapp.HandleAPI(%q, %q, %s.%s)\n", method, route.Path, route.ImportAlias, method)
				continue
			}
			fmt.Fprintf(output, "\tapp.HandleAPI(%q, %q, %s.%s, %s...)\n", method, route.Path, route.ImportAlias, method, middleware)
		}
		if route.HasWebSocket {
			options := "web.SocketOptions{}"
			if route.HasSocketOptions {
				options = route.ImportAlias + ".WebSocketOptions()"
			}
			if middleware == "nil" {
				fmt.Fprintf(output, "\tapp.WebSocket(%q, %s, %s.WEBSOCKET)\n", route.Path, options, route.ImportAlias)
			} else {
				fmt.Fprintf(output, "\tapp.WebSocket(%q, %s, %s.WEBSOCKET, %s...)\n", route.Path, options, route.ImportAlias, middleware)
			}
		}
	}
	if errorPage != nil {
		output.WriteString("\tapp.HandleFunc(\"GET /\", func(w http.ResponseWriter, r *http.Request) { app.HandleError(w, r, web.NotFound(\"Page not found\")) })\n")
	}
	output.WriteString("}\n\n")
}

func writePageMiddleware(output *bytes.Buffer, page routeView, layouts map[string]routeView) {
	fmt.Fprintf(output, "func %sMiddleware() []web.Middleware {\n", page.Name)
	output.WriteString("\tvar middleware []web.Middleware\n")
	for _, layout := range layoutsForDirectory(page.Directory, layouts) {
		if layout.HasMiddleware {
			fmt.Fprintf(output, "\tmiddleware = append(middleware, %s.LayoutMiddleware()...)\n", layout.ImportAlias)
		}
	}
	if page.HasMiddleware {
		fmt.Fprintf(output, "\tmiddleware = append(middleware, %s.PageMiddleware()...)\n", page.ImportAlias)
	}
	output.WriteString("\treturn middleware\n}\n\n")
}

func writePageRenderer(output *bytes.Buffer, page routeView, layouts map[string]routeView) {
	fmt.Fprintf(output, "func render%sRoute(w io.Writer, request *http.Request) error {\n", page.Name)
	output.WriteString("\tcontext := web.ContextFor(request)\n")
	fmt.Fprintf(output, "\tcontent0 := func(w io.Writer) error { if _, err := io.WriteString(w, %s); err != nil { return err }; props, err := %s.Page(context); if err != nil { return err }; if err := Render%s(w, props); err != nil { return err }; _, err = io.WriteString(w, %s); return err }\n",
		strconv.Quote(`<north-route-segment data-north-route-kind="page" data-north-route-segment="`+page.Path+`">`), page.ImportAlias, page.Name, strconv.Quote(`</north-route-segment>`))
	layoutChain := layoutsForDirectory(page.Directory, layouts)
	for index := len(layoutChain) - 1; index >= 0; index-- {
		contentIndex := len(layoutChain) - index
		layout := layoutChain[index]
		if layout.Directory == "." {
			fmt.Fprintf(output, "\tcontent%d := func(w io.Writer) error { props, err := %s.Layout(context); if err != nil { return err }; return Render%s(w, props, content%d) }\n", contentIndex, layout.ImportAlias, layout.Name, contentIndex-1)
			continue
		}
		fmt.Fprintf(output, "\tcontent%d := func(w io.Writer) error { if _, err := io.WriteString(w, %s); err != nil { return err }; props, err := %s.Layout(context); if err != nil { return err }; if err := Render%s(w, props, content%d); err != nil { return err }; _, err = io.WriteString(w, %s); return err }\n",
			contentIndex, strconv.Quote(`<north-route-segment data-north-route-kind="layout" data-north-route-segment="`+layout.Directory+`">`), layout.ImportAlias, layout.Name, contentIndex-1, strconv.Quote(`</north-route-segment>`))
	}
	fmt.Fprintf(output, "\treturn content%d(w)\n}\n\n", len(layoutChain))
}

func layoutsForDirectory(directory string, layouts map[string]routeView) []routeView {
	directories := []string{"."}
	if directory != "." {
		parts := strings.Split(directory, "/")
		for index := range parts {
			directories = append(directories, strings.Join(parts[:index+1], "/"))
		}
	}
	var result []routeView
	for _, candidate := range directories {
		if layout, exists := layouts[candidate]; exists {
			result = append(result, layout)
		}
	}
	return result
}
