package web

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"net/http"
)

const (
	csrfCookieName = "northframe_csrf"
	csrfLocalName  = "northframe.csrf.token"
)

// CSRF protects unsafe requests with a signed-random double-submit token. The
// embedded browser runtime adds the matching hidden field to non-GET forms.
func CSRF() Middleware {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
			cookie, err := request.Cookie(csrfCookieName)
			if err != nil || cookie.Value == "" {
				cookie = &http.Cookie{
					Name: csrfCookieName, Value: newCSRFToken(), Path: "/",
					Secure: request.TLS != nil, HttpOnly: false, SameSite: http.SameSiteStrictMode,
				}
				http.SetCookie(writer, cookie)
			}
			SetLocal(request, csrfLocalName, cookie.Value)
			if isSafeMethod(request.Method) {
				next.ServeHTTP(writer, request)
				return
			}
			token := request.Header.Get("X-CSRF-Token")
			if token == "" {
				if err := request.ParseForm(); err == nil {
					token = request.Form.Get("_northframe_csrf")
				}
			}
			if subtle.ConstantTimeCompare([]byte(cookie.Value), []byte(token)) != 1 {
				http.Error(writer, "invalid CSRF token", http.StatusForbidden)
				return
			}
			next.ServeHTTP(writer, request)
		})
	}
}

// CSRFToken returns the request's double-submit token for server-rendered
// forms. It includes a token generated by CSRF middleware during this request.
func CSRFToken(ctx *Context) string {
	if ctx == nil {
		return ""
	}
	if token, ok := ctx.Locals[csrfLocalName].(string); ok {
		return token
	}
	if ctx.Request != nil {
		if cookie, err := ctx.Request.Cookie(csrfCookieName); err == nil {
			return cookie.Value
		}
	}
	return ""
}

func newCSRFToken() string {
	buffer := make([]byte, 32)
	if _, err := rand.Read(buffer); err != nil {
		panic("northframe: cannot generate CSRF token: " + err.Error())
	}
	return base64.RawURLEncoding.EncodeToString(buffer)
}

func isSafeMethod(method string) bool {
	return method == http.MethodGet || method == http.MethodHead || method == http.MethodOptions || method == http.MethodTrace
}
